basePath: /
definitions:
  models.HealthCheckResponse:
    properties:
      status:
        type: string
    type: object
host: localhost:80
info:
  contact: {}
  description: This is a backend microservice for shorti.fy Redirect.
  title: shorti.fy - Redirect
  version: "1.0"
paths:
  /{hashKey}:
    get:
      description: redirect to original url
      parameters:
      - description: short url key
        in: path
        name: hashKey
        required: true
        type: string
      responses:
        "301":
          description: Moved Permanently
        "500":
          description: Internal Server Error
      summary: Reader
      tags:
      - shortify
  /healthcheck:
    get:
      description: Check Server Health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HealthCheckResponse'
      summary: Check HealthCheckStatus
      tags:
      - healthcheck
swagger: "2.0"
