apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shortify-writer.name" . }}
  namespace: {{ include "shortify-writer.name" . }}
data:
  APP_PORT: "{{ .Values.config.appPort }}"
  AWS_REGION: "{{ .Values.config.awsRegion }}"
  APP_DOMAIN: "{{ .Values.config.appDomain }}"

