apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-helper-secrets
  namespace: {{ include "shortify-writer.name" . }}
stringData:
  AWS_SECRET_ACCESS_KEY: "{{ .Values.config.awsAccessToken }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.config.awsAccessID }}"
  AWS_ACCOUNT: "{{ .Values.config.awsAccount }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "shortify-writer.name" . }}
  name: ecr-registry-helper-cm
data:
  AWS_REGION: {{ .Values.config.awsRegion }}
  DOCKER_SECRET_NAME: {{ .Values.config.dockerSecretName }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ include "shortify-writer.name" . }}
  name: ecr-registry-helper
spec:
  schedule: "0 */10 * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-health-check
          containers:
            - name: ecr-registry-helper
              image: odaniait/aws-kubectl:latest
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: ecr-registry-helper-secrets
                - configMapRef:
                    name: ecr-registry-helper-cm
              command:
                - /bin/sh
                - -c
                - |-
                  ECR_TOKEN=`aws ecr get-login-password --region ${AWS_REGION}`
                  kubectl delete secret --ignore-not-found $DOCKER_SECRET_NAME
                  kubectl create secret docker-registry $DOCKER_SECRET_NAME \
                  --docker-server=https://${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com \
                  --docker-username=AWS \
                  --docker-password="${ECR_TOKEN}"
                  echo "Secret was successfully updated at $(date)"
          restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "shortify-writer.name" . }}
  name: sa-health-check
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ include "shortify-writer.name" . }}
  name: role-full-access-to-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["regcred"]
    verbs: ["delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ include "shortify-writer.name" . }}
  name: health-check-role-binding
subjects:
  - kind: ServiceAccount
    name: sa-health-check
    apiGroup: ""
roleRef:
  kind: Role
  name: role-full-access-to-secrets
  apiGroup: ""
---