apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shortify-writer.name" . }}
  namespace: {{ include "shortify-writer.name" . }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.config.awsAccessID | b64enc}}
  AWS_SECRET_ACCESS_TOKEN: {{ .Values.config.awsAccessToken | b64enc }}