apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shortify-redirect.name" . }}
  namespace: {{ include "shortify-redirect.name" . }}
data:
  APP_PORT: "{{ .Values.config.appPort }}"
  AWS_REGION: "{{ .Values.config.awsRegion }}"
  REDIS_HOST: {{ .Values.config.redisHost }}
  REDIS_PASSWORD: {{ .Values.config.redisPassword }}


