name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - redirect/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file redirect/Dockerfile --tag shortify-redirect:$(date +%s)
